site_name: "ASIC Interview Questions"
site_url: "https://yourwebsite.com"
repo_url: "https://github.com/yourrepo"
edit_uri: "edit/main/docs/"

theme:
  name: "material"
  font:
    text: "Roboto"
    code: "Roboto Mono"
    heading: "Merriweather"
  palette:
    primary: "blue"
    accent: "indigo"
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - Digital Design: questions/digital.md
  - Verification: questions/verification.md
  - Physical Design: questions/physical.md
  - Synthesis & STA: questions/synthesis.md
  - DFT: questions/dft.md
  - Mixed-Signal Design: questions/mixed_signal.md
  - Low Power Design: questions/low_power.md
  - Protocols: questions/protocol.md
  - About: about.md

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - admonition
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.arithmatex
  - pymdownx.tasklist
  - pymdownx.tilde

plugins:
  - search
  - awesome-pages
  - mermaid2
