site_name: "ASIC Interview Questions"
site_url: "https://yourwebsite.com"
repo_url: "https://github.com/yourrepo"
edit_uri: "edit/main/docs/"

theme:
  name: "material"
  font:
    text: "Roboto"
    code: "Roboto Mono"
    heading: "Merriweather"
  palette:
    primary: "blue"
    accent: "indigo"
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - navigation.expand

extra_css:
  - stylesheets/custom.css

nav:
  - Home: index.md
  - Digital Design:
      - Overview: questions/digital.md
      - Logic Design Questions: questions/digital/logic-design.md
      - Clocking, Clock Dividers, and Reset Questions: questions/digital/clocking.md
      - Clock Domain Crossing (CDC) Questions: questions/digital/cdc.md
      - Power-Related Questions: questions/digital/power.md
      - Digital Filter Questions (FIR, IIR and CIC): questions/digital/digital-filters.md
  - Protocols:
      - Overview: questions/protocols.md
      - APB (Advanced Peripheral Bus): questions/protocols/apb.md
      - AHB (Advanced High-performance Bus): questions/protocols/ahb.md
      - AXI (Advanced eXtensible Interface): questions/protocols/axi.md
      - PCIe (Peripheral Component Interconnect Express): questions/protocols/pcie.md
      - DDR (Double Data Rate Memory): questions/protocols/ddr.md
      - USB (Universal Serial Bus): questions/protocols/usb.md
  - Verification: questions/verification.md
  - Physical Design: questions/physical.md
  - Synthesis & STA: questions/synthesis.md
  - DFT: questions/dft.md
  - Mixed-Signal Design: questions/mixed_signal.md

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - admonition
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.arithmatex
  - pymdownx.tasklist
  - pymdownx.tilde
  - pymdownx.inlinehilite

plugins:
  - search
  - awesome-pages
  - mermaid2
